name: yourpen_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_gradient_button: ^0.0.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway.ttf
    - family: GentiumBasic
      fonts:
        - asset: assets/fonts/Gentium-Basic.ttf
